# Generated by Django 4.2.1 on 2023-09-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giris', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
